name: 'grafana in GitHub Actions'
description: 'Start a grafana as Docker container'

branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  version:
    description: 'grafana version to use'
    required: false
    default: 'latest'
  ports:
    description: 'Port mappings in a [host]:[container] format, delimited by spaces (example: "8086:8086")'
    required: false
    default: '8086:8086'
  container-name:
    description: 'The name of the spawned Docker container (can be used as hostname when accessed from other containers)'
    required: false
    default: 'grafana'
  gf_security_admin_user: 
    description: security_admin_user
    required: false
    default: admin
  gf_security_admin_password: 
    description: security_admin_password
    required: false
    default: password
  gf_auth_anonymous_enabled: 
    description: auth_anonymous_enabled
    required: false
    default: "false"
  gf_auth_basic_enabled: 
    description: auth_basic_enabled
    required: false
    default: "true"
  gf_auth_generic_oauth_enabled: 
    description: auth_generic_oauth_enabled
    required: false
    default: "false"
  gf_auth_proxy_enabled: 
    description: auth_proxy_enabled
    required: false
    default: "false"
  gf_auth_ldap_enabled: 
    description: auth_ldap_enabled
    required: false
    default: "false"
  gf_auth_grafana_enabled: 
    description: auth_grafana_enabled
    required: false
    default: "true"
  gf_auth_grafana_api_key: 
    description: auth_grafana_api_key
    required: false
    default: u4OwnMQmaqcHhwjjhQdtqUSl9OQ8+wE7pQmMq2h3NQn6LBgxPtY8lA1nNHncUepF

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.ports }}
    - ${{ inputs.container-name }}
    - ${{ inputs.gf_security_admin_user }}
    - ${{ inputs.gf_security_admin_password }}
    - ${{ inputs.gf_auth_anonymous_enabled }}
    - ${{ inputs.gf_auth_basic_enabled }}
    - ${{ inputs.gf_auth_generic_oauth_enabled }}
    - ${{ inputs.gf_auth_proxy_enabled }}
    - ${{ inputs.gf_auth_ldap_enabled }}
    - ${{ inputs.gf_auth_grafana_enabled }}
    - ${{ inputs.gf_auth_grafana_api_key }}
